---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-page-uat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/application-repository: landing-page
    argocd.argoproj.io/deployment-id: "4904864256"
    argocd.argoproj.io/environment: "uat"
  labels:
    layer: applications
    service: landing-page
    environment: uat
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: landing-page-uat
    server: https://192.168.200.102:443
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: ghcr.io/<your-org>/landing-page/charts/application
      targetRevision: 0.1.0-rc.0 # Will be updated by deploy workflow
      chart: landing-page
      helm:
        values: |
          ingress:
            enabled: true
            hosts:
              - host: landing-page-uat.<user-xx>.hoverkraft.cloud
                paths:
                  - path: /

                    pathType: ImplementationSpecific
          deploymentId: "4904864256"
