---
name: Internal - Common Continuous Integration tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@b553a696531fbd36743ccbb0c76c717971b8acdb # 0.35.4
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    with:
      codeql-languages: "" # FIXME: Let default value when CodeQL will be available (paid feature)
