---
name: Internal - Common Continuous Integration tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@6718ae98e8b6e009f8f2790af074daa1a06946c2 # 0.36.2
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    with:
      codeql-languages: "" # FIXME: Let default value when CodeQL will be available (paid feature)
